/**
 * @module content/wealth-codes
 * @description CR-G — founder-authored Multigenerational Wealth Codes,
 * carried VERBATIM from v1 per founder verdict 2026-08-24 ("wealth codes
 * stay word-for-word"). Extracted programmatically from
 * satnam_pub/src/components/pages/FamilyFoundryLandingPage.tsx — do NOT
 * edit prose here; edits belong in v1 first, then re-extract.
 *
 * **bold** markers preserve v1 emphasis spans.
 */

export interface WealthCode {
  readonly title: string;
  readonly body: string;
}

export const WEALTH_CODES: ReadonlyArray<WealthCode> = [
  {
    title: "Code #018: Business + Kingdom",
    body:
"Most wealthy families eventually lose the plot because they try to make the family purely emotional, or purely corporate. **Both are wrong.**\n\n\n\nThe purely emotional family operates on feelings, nostalgia, and unspoken expectations. There are no clear roles, no documented processes, no accountability structures. Decisions are made based on who speaks loudest or who guilt-trips most effectively. Money flows based on sentiment rather than strategy. This creates resentment, confusion, and eventually—collapse.\n\n\n\nThe purely corporate family treats relationships like transactions. Everything is measured, optimized, and monetized. Family dinners feel like board meetings. Children are raised like employees. Love is conditional on performance metrics. This creates emotional distance, rebellion, and a legacy that feels hollow—even when the balance sheet looks impressive.\n\n\n\n**A successful legacy must be operationally efficient AND spiritually anchored.** Without structure, familiarity turns into dysfunction, and money becomes the battleground. Without soul, the family becomes cold, performative, and extractive.\n\n\n\nThis is why the greatest families in history—from the Medici to the Rothschilds, from ancient dynasties to modern family offices—understood that you must **run the family like a business, but govern it like a kingdom.**\n\n\n\nThe business side provides: clear roles, documented systems, transparent ledgers, annual reviews, formalized succession planning, and legacy planning that extends beyond the founders. This is the operational backbone that prevents chaos.\n\n\n\nThe kingdom side provides: meetings that open with blessing and ceremony, roles inherited with ritual and reverence, elders consulted with honor, and sacred stewardship of resources. This is the spiritual anchor that prevents soullessness.\n\n\n\n**When both live in balance**, you create a lineage that knows its mission, a treasury that funds generational vision, and a culture of reverence—not just ROI. You create a family that can weather storms, navigate transitions, and build something that lasts beyond your lifetime.",
  },
  {
    title: "Code #021: Structure Belongs in the Home",
    body:
"**Children raised in chaos become adults who resist governance.** The home is the first kingdom. There is no dynasty without order, and there is no order without structure that starts inside the home.\n\n\n\nMany modern parents fear structure. They worry it will stifle creativity, damage self-esteem, or create resentment. So they opt for permissiveness disguised as \"freedom.\" They let children interrupt adult conversations. They negotiate with toddlers. They avoid consequences because they want to be liked. They create homes where chaos is normalized and boundaries are optional.\n\n\n\nThe result? Children who grow up unable to self-regulate, unable to delay gratification, unable to respect authority, and unable to lead themselves—let alone lead others. These children become adults who resist any form of governance because they never learned to govern themselves.\n\n\n\n**Children are shaped by what happens repeatedly**—not by what you say occasionally. They learn from patterns, not promises. They internalize what is consistently enforced, not what is occasionally mentioned.\n\n\n\nDoes \"no\" mean no? Or does it mean \"maybe if you whine enough\"? Are interruptions corrected immediately, or tolerated until frustration boils over? Are parents in alignment on rules and consequences, or do children learn to play one against the other? Do mornings have rhythm and routine, or is every day a chaotic scramble? Do consequences follow through consistently, or are they threatened but rarely enforced?\n\n\n\nStructure in the home doesn't mean military rigidity. It means predictable rhythms, clear expectations, consistent consequences, and aligned leadership. It means children know what to expect, what is expected of them, and what happens when expectations aren't met.\n\n\n\n**Govern the home. Govern early. Govern quietly—but without apology.** Start when they're young, before bad habits calcify. Govern with calm consistency, not emotional outbursts. Govern without needing to justify every decision to a five-year-old.\n\n\n\nChildren raised in structure don't become robotic. They become **sovereign**. They learn self-discipline, delayed gratification, respect for authority, and the capacity to lead. They become adults who can govern themselves, their families, and their wealth—because they learned governance at home.",
  },
  {
    title: "Code #006: Wealth Is Not the Goal. Stewardship Is.",
    body:
"**Most stop at acquisition. Dynasties begin at administration.** Wealth can be made in one generation, but it is rarely kept without structure, philosophy, and ritual.\n\n\n\nThe first generation builds. They hustle, sacrifice, take risks, and accumulate. They focus on making money—and they're often very good at it. But making money and keeping money are two entirely different skill sets.\n\n\n\nThe second generation inherits. They didn't build it, so they don't have the same relationship with it. They may respect it, or they may resent it. They may preserve it, or they may squander it. Without intentional stewardship training, they often do both—preserving some while squandering the rest.\n\n\n\nThe third generation destroys. This is the infamous \"shirtsleeves to shirtsleeves in three generations\" pattern. By the third generation, the wealth is gone—not because they're stupid, but because **no one taught them stewardship.**\n\n\n\nFamilies who last more than three generations understand something fundamental: **wealth is not the finish line. It is the foundation.** The goal is not to accumulate as much as possible. The goal is to create a system that preserves, grows, and deploys wealth in alignment with family values—across generations.\n\n\n\nThese families focus on **how wealth is held, where it flows, who has access, what it's aligned to, and why.** They create:\n\n\n\n**Trusts** that protect assets from creditors, lawsuits, and poor decisions\n**Family constitutions** that codify values, governance structures, and decision-making processes\n**Education programs** that train each generation in financial literacy, business acumen, and stewardship principles\n**Governance councils** that make major decisions collectively, not individually\n**Rituals and ceremonies** that reinforce family identity and values\n\n\n\nThey ensure every major financial decision echoes back to **legacy—not lifestyle.** They don't ask, \"Can we afford this?\" They ask, \"Does this serve the lineage?\"\n\n\n\nThey understand that wealth without stewardship becomes a curse. It creates entitlement, destroys work ethic, and breeds resentment. But wealth WITH stewardship becomes a tool for multigenerational impact.\n\n\n\nThe goal is not more. **The goal is meaningful continuity.** Stewardship is the difference between inheritance and chaos. And the true aristocracy understands: **Wealth is not the finish line. It is the foundation.**\n\n\n\n\n\n\n— Teachings by Namaste` Moore\n\n\nLearn more from Namaste` Moore →",
  },
];
